### ISSUE TITLE
Vásárló felvétele

### ISSUE THREAD

**Issue by istvan92l** [Marci1395/Penztargep#3]
Új vásárló felvételénél valami hibát dob.

**Comment by markesztivadar** [comment]
Köszönöm hogy jelezted, későbbiekben javítom az említett hibát!


Küldte a Windows 10 Posta

Feladó: istvan92l
Elküldve: 2017. december 9., szombat 17:42
Címzett: Marci1395/Penztargep
Másolatot kap: markesztivadar; Assign
Tárgy: [Marci1395/Penztargep] Vásárló felvétele (#3)

Új vásárló felvételénél valami hibát dob.

**Comment by markesztivadar** [comment]
Egy változó neve okozta a hibát, javítva!

Küldte a Windows 10 Posta

Feladó: istvan92l
Elküldve: 2017. december 9., szombat 17:42
Címzett: Marci1395/Penztargep
Másolatot kap: markesztivadar; Assign
Tárgy: [Marci1395/Penztargep] Vásárló felvétele (#3)

Új vásárló felvételénél valami hibát dob.
